### ISSUE TITLE
Bridge side todo list.

### ISSUE THREAD

**Issue by petertheprocess** [petertheprocess/side_chain_dapp#1]
## chain side todo
- [x] set a lower bridge node lock period rather than 1 day.
- [x] write script to launch multiple bridge node at once.
- [x] find a way to display the bridgePool status (how many valid bridge node are working.)
- [x] interact the brideToken with DiceGame balance.
## front end side todo
- [x] basic ui for testing and demo showing. (either vis react or remix)
